{
    'name': 'NuYu Social Media Integration - TEST',
    'version': '16.0.2.0.0',
    'category': 'Marketing',
    'summary': 'Social media system for NuYu - Testing Phase',
    'depends': ['base', 'contacts', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/customer_enhancement_views.xml',
        'views/social_platform_views.xml',
        'views/social_campaign_views.xml',
        'views/social_marketing_dashboard.xml',
        'views/birthday_automation_views.xml',
        'views/whatsapp_connector_views.xml',
        'views/elena_main_menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}